### ISSUE TITLE
Select Only Those cells where finger drags

### ISSUE THREAD

**Issue by gurpalrajput** [ShaneQi/SwipeSelectingCollectionView#2]
I need to select only those cells on which user drag fingers, more or less... I don't want to select all cells under begin Index And End Index

**Comment by ShaneQi** [comment]
Sorry for the late response. 

https://github.com/ShaneQi/SwipeSelectingCollectionView/blob/master/Sources/SwipeSelectingCollectionView.swift#L63

This is where the lib finds out which cell your finger is on. The code below in that method is for calculating the indices between the begin index and end index. You can make the changes there to achieve your goal.
